[Simulation]

    # seed = 1234
    tickunit = 'd'
    GlobalSetting = false
    startdate = '2024.01.01'
    enddate = '2024.12.31'
    [Simulation.StartCondition]
        type = "InfectedFraction"
        fraction = 0.001
        pathogen = "Covid19"   # BE AWARE, THAT NAME MUST BE THE SAME AS IN TOML SECTION

    [Simulation.StopCriterion]
        type = "TimesUp"
        limit = 365

[Population]
    n = 100_000
    avg_household_size = 3
    avg_office_size = 5
    avg_school_size = 100
    empty = false

[Pathogens]

    [Pathogens.Covid19]
        [Pathogens.Covid19.transmission_function]
            type = "ConstantTransmissionRate"
            [Pathogens.Covid19.transmission_function.parameters]
                transmission_rate = 0.10

        [Pathogens.Covid19.onset_of_symptoms]
            distribution = "Poisson"
            parameters = [3]


        [Pathogens.Covid19.time_to_recovery]
            distribution = "Poisson"
            parameters = [7]

        [Pathogens.Covid19.onset_of_severeness]
            distribution = "Poisson"
            parameters = [3]

        [Pathogens.Covid19.infectious_offset]
            distribution = "Poisson"
            parameters = [1]

        [Pathogens.Covid19.mild_death_rate]
            distribution = "Binomial"
            parameters = [1, 0.0]

        [Pathogens.Covid19.severe_death_rate]
            distribution = "Binomial"
            parameters = [1, 0.05]

        [Pathogens.Covid19.critical_death_rate]
            distribution = "Binomial"
            parameters = [1, 0.2]

        [Pathogens.Covid19.hospitalization_rate]
            distribution = "Binomial"
            parameters = [1, 0.3]

        [Pathogens.Covid19.ventilation_rate]
            distribution = "Binomial"
            parameters = [1, 0.3]

        [Pathogens.Covid19.icu_rate]
            distribution = "Binomial"
            parameters = [1, 0.3]

        [Pathogens.Covid19.time_to_hospitalization]
            distribution = "Poisson"
            parameters = [7]

        [Pathogens.Covid19.time_to_icu]
            distribution = "Poisson"
            parameters = [7]

        [Pathogens.Covid19.length_of_stay]
            distribution = "Poisson"
            parameters = [7]

        [Pathogens.Covid19.dpr]
        # Matrix with Disease Progression
            age_groups = ["0+"]
            disease_compartments = ["Asymptomatic", "Mild", "Severe", "Critical"]
            stratification_matrix = [[0.4, 0.45, 0.1, 0.05]]

[Settings]

    [Settings.Household]
        [Settings.Household.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.Household.contact_sampling_method.parameters]
                    contactparameter = 1.5

    [Settings.Office]
        [Settings.Office.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.Office.contact_sampling_method.parameters]
                    contactparameter = 0.4
                    
    [Settings.School]
        [Settings.School.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.School.contact_sampling_method.parameters]
                    contactparameter = 0.3

    [Settings.SchoolClass]
        [Settings.SchoolClass.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.SchoolClass.contact_sampling_method.parameters]
                    contactparameter = 0.5

    [Settings.Municipality]
        [Settings.Municipality.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.Municipality.contact_sampling_method.parameters]
                    contactparameter = 1.3

    [Settings.WorkplaceSite]
        [Settings.WorkplaceSite.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.WorkplaceSite.contact_sampling_method.parameters]
                    contactparameter = 0.1

    [Settings.SchoolComplex]
        [Settings.SchoolComplex.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.SchoolComplex.contact_sampling_method.parameters]
                    contactparameter = 0.2

    [Settings.SchoolYear]
        [Settings.SchoolYear.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.SchoolYear.contact_sampling_method.parameters]
                    contactparameter = 0.4


    [Settings.Department]
        [Settings.Department.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.Department.contact_sampling_method.parameters]
                    contactparameter = 0.3

    [Settings.Workplace]
        [Settings.Workplace.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.Workplace.contact_sampling_method.parameters]
                    contactparameter = 0.2

                    
    [Settings.GlobalSetting]
        [Settings.GlobalSetting.contact_sampling_method]
                type = "ContactparameterSampling"

                [Settings.GlobalSetting.contact_sampling_method.parameters]
                    contactparameter = 0.0
